import { NextResponse } from 'next/server';
import dbConnect from '@/lib/mongodb';
import { Issue, Project, Requirement } from '@/models';
import { Octokit } from '@octokit/rest';

export async function GET(
    req: Request,
    { params }: { params: Promise<{ id: string }> }
) {
    const { id } = await params;
    await dbConnect();

    try {
        const project = await Project.findById(id);
        if (!project) {
            return NextResponse.json({ error: "Project not found" }, { status: 404 });
        }

        // Find all issues with PRs
        const issuesWithPrs = await Issue.find({
            projectId: id,
            prUrl: { $exists: true, $ne: null }
        }).populate({ path: 'requirementId', strictPopulate: false }).sort({ updatedAt: -1 });

        const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

        // Enrich with live GitHub status
        const enrichedPrs = await Promise.all(issuesWithPrs.map(async (issue) => {
            try {
                // Parse URL: https://github.com/owner/repo/pull/number
                const urlParts = issue.prUrl.split('/');
                const owner = urlParts[3];
                const repo = urlParts[4];
                const pullNumber = parseInt(urlParts[6]);

                const { data: pr } = await octokit.pulls.get({
                    owner,
                    repo,
                    pull_number: pullNumber
                });

                const { data: files } = await octokit.pulls.listFiles({
                    owner,
                    repo,
                    pull_number: pullNumber
                });

                return {
                    issueId: issue._id,
                    issueTitle: issue.title,
                    requirement: issue.requirementId,
                    prUrl: issue.prUrl,
                    prStatus: pr.state, // open, closed, merged (merged is actually a separate check usually)
                    isMerged: pr.merged,
                    ghTitle: pr.title,
                    filesChanged: files.map(f => f.filename),
                    aiExplanation: issue.aiExplanation || "This PR was generated by the AI Issue Fixer to resolve the linked issue.",
                    createdAt: pr.created_at,
                    mergedAt: issue.mergedAt
                };
            } catch (err) {
                console.error(`Error fetching PR status for ${issue.prUrl}:`, err);
                return {
                    issueId: issue._id,
                    issueTitle: issue.title,
                    prUrl: issue.prUrl,
                    error: "Could not fetch status from GitHub"
                };
            }
        }));

        return NextResponse.json(enrichedPrs);
    } catch (error: any) {
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
